### ISSUE TITLE
Tests failing with recent commit

### ISSUE THREAD

**Issue by helaili** [Microsoft/azure-devops-node-api#124]
Trying to debug #123, I've been trying the samples and then tests but no luck. `npm test` fails with: 

```
> vso-node-api@6.2.8-preview test /Users/alain/Documents/workspace/vsts-node-api
> node make.js test

> tsc --outDir /Users/alain/Documents/workspace/vsts-node-api/_build
typings/globals/underscore/index.d.ts(3760,34): error TS1122: A tuple type element list cannot be empty.
/Users/alain/Documents/workspace/vsts-node-api/node_modules/shelljs/src/common.js:417
      if (config.fatal) throw e;
                        ^

Error: exec: internal error
    at Object.error (/Users/alain/Documents/workspace/vsts-node-api/node_modules/shelljs/src/common.js:128:27)
    at _exec (/Users/alain/Documents/workspace/vsts-node-api/node_modules/shelljs/src/exec.js:292:12)
    at /Users/alain/Documents/workspace/vsts-node-api/node_modules/shelljs/src/common.js:350:23
    at run (/Users/alain/Documents/workspace/vsts-node-api/make.js:14:14)
    at Function.target.build (/Users/alain/Documents/workspace/vsts-node-api/make.js:29:5)
    at Object.global.target.(anonymous function) [as build] (/Users/alain/Documents/workspace/vsts-node-api/node_modules/shelljs/make.js:36:40)
    at Function.target.test (/Users/alain/Documents/workspace/vsts-node-api/make.js:41:12)
    at Object.global.target.(anonymous function) [as test] (/Users/alain/Documents/workspace/vsts-node-api/node_modules/shelljs/make.js:36:40)
    at /Users/alain/Documents/workspace/vsts-node-api/node_modules/shelljs/make.js:48:27
    at Array.forEach (<anonymous>)
npm ERR! Test failed.  See above for more details.
``` 

Seems like the break came with #64 as [d60e4b7](https://github.com/Microsoft/vsts-node-api/commit/d60e4b7c4035c39cd2ab6cc03a1f1b718a7ea060) works fine.

**Comment by stephenmichaelf** [comment]
@helaili Are you still having an issue with running tests? They should be working now. Can you get latest and try?

**Comment by helaili** [comment]
Not using the API anymore but thanks for the follow up.
