### ISSUE TITLE
The WebApi constructor reads package.json from the current working directory

### ISSUE THREAD

**Issue by MortenHoustonLudvigsen** [Microsoft/azure-devops-node-api#243]
### Environment
Node version: 10.0.0
Npm version: 5.6.0
OS and version: Windows 10 Pro
azure-devops-node-api version: 6.6.2

### Issue Description

The WebApi constructor tries to get the version of azure-devops-node-api, for use in the user agent string, by reading `package.json` from the current working directory.

### Expected behaviour

The WebApi constructor should get the version of azure-devops-node-api by reading `package.json` from the same directory as `WebApi.js`.

### Actual behaviour

The WebApi constructor throws an error if `package.json` does not exist in the current working directory.

### Steps to reproduce
1. Create a file `test.js` in a directory, that does not have a `package.json` file:
  ```javascript
  const { WebApi, getBasicHandler } = require('azure-devops-node-api');
  const connection = new WebApi('https://zzzzzz.visualstudio.com', getBasicHandler('donald', 'duck'));
  ```
2. Make sure azure-devops-node-api version 6.6.2 is installed in a parent directory.
3. Run:
  ```
  node test.js
  ```
4. I get the following error:
  ```
  fs.js:110
      throw err;
      ^

  Error: ENOENT: no such file or directory, open 'package.json'
      at Object.fs.openSync (fs.js:545:3)
      at Object.fs.readFileSync (fs.js:451:33)
      at new WebApi (X:\fiks-tools\fiks-udvikler-tools\fiks-udvikler-tools\node_modules\azure-devops-node-api\WebApi.js:136:46)
      at Object.<anonymous> (X:\fiks-tools\fiks-udvikler-tools\fiks-udvikler-tools\test\slam.js:2:20)
      at Module._compile (internal/modules/cjs/loader.js:678:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
      at Module.load (internal/modules/cjs/loader.js:589:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
      at Function.Module._load (internal/modules/cjs/loader.js:520:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
  ```
5.

**Comment by jarethuk** [comment]
@damccorm Can this be released please?

**Comment by damccorm** [comment]
@bryanmacfarlane can you release? Only changes are this and a patch version bump.

**Comment by damccorm** [comment]
6.6.3 has been published, sorry for the delay.
