### ISSUE TITLE
createThread in Git API throws error: 'Both a source and target reference is required'

### ISSUE THREAD

**Issue by DrewHiggins** [microsoft/azure-devops-node-api#306]
### Environment
Node version: 8.15.1
Npm version: 6.4.1
OS and version: Windows 10
azure-devops-node-api version: 7.2.0

### Issue Description
I'm running a script in a build agent that is supposed to comment on pull requests in Azure DevOps with information about the build in a new thread. However, when calling the `createThread` method in `IGitApi` with all required parameters (a new thread object, a repo name, a PR ID number, and project name), it throws a 400 error from the server.

This only happens with this method; I tried calling the `getPullRequest` method to see if there was an issue with my PR information and that call succeeded. Here is the code:

      const gitApi: IGitApi = await connection.getGitApi();
      const testPr: GitPullRequest = await gitApi.getPullRequest(
        repositoryName, parseInt(pullRequestId, 2), projectName
      );
      console.log(JSON.stringify(testPr)); // <-- this prints an object with PR info successfully
      await gitApi.createThread(thread, repositoryName, parseInt(pullRequestId, 2), projectName); // <-- this throws an error

This method works one a test tenant I was working on just fine, but throws an error on a different one. The error `Parameter name: Both a source and target reference is required.` looks to be coming from the server, but I don't know if it is a problem with my tenant or with how the library is constructing the REST call. Can anyone provide guidance on what this error means or why it might be happening?

### Expected behaviour
I expect that it will add a new thread on the specified PR with the specified content.

### Actual behaviour
The library throws the following error:

```
{ Error: Invalid argument value.
Parameter name: Both a source and target reference is required.
    at RestClient.<anonymous> (/home/vsts/work/1/s/common/temp/node_modules/typed-rest-client/RestClient.js:173:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/1/s/common/temp/node_modules/typed-rest-client/RestClient.js:6:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  statusCode: 400,
  result: 
   { '$id': '1',
     innerException: null,
     message: 'Invalid argument value.\r\nParameter name: Both a source and target reference is required.',
     typeName: 'Microsoft.TeamFoundation.SourceControl.WebServer.InvalidArgumentValueException, Microsoft.TeamFoundation.SourceControl.WebServer',
     typeKey: 'InvalidArgumentValueException',
     errorCode: 0,
     eventId: 0 } }
```

### Steps to reproduce
1. Initialize a new WebApi object with `new WebApi(orgUrl, authHandler)`
2. Call the web API object to get an instance of the GitApi class
3. Call `createThread(thread, repoName, pullRequest, projectName)` on the Git API instance
4. Run this JS code on an Azure DevOps hosted build agent.

### Logs
See above

**Comment by stephenmichaelf** [comment]
Hey Drew,

This library is a wrapper around the REST api calls. It looks like you're missing some data in the request object.

Have you tried making a raw HTTP request with something like Postman and seeing what response you get?

**Comment by DrewHiggins** [comment]
Making a raw request works correctly, as does this call from JS using `fetch()`:

````
const base64Token: string = Buffer.from(':' + process.env.SYSTEM_ACCESSTOKEN!).toString('base64');
fetch(
      `https://dev.azure.com/{org}/{project}/_apis/git/repositories/{repo}/pullRequests/{pullRequestId}/threads?api-version=5.0`,
      {
        headers: {
          'Accept': 'application/json',
          'Authorization': 'Basic ' + base64Token,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(thread),
        method: 'POST'
      }
    )
      .then(res => res.json())
````

**Comment by stephenmichaelf** [comment]
Can you check the request from the lib using Fiddler and diff the two and see where it's different?

Thanks!

**Comment by damccorm** [comment]
@DrewHiggins any update on this?

**Comment by stephenmichaelf** [comment]
Closing due to inactivity. Please reopen if you continue to have the issue. Thanks!
