### ISSUE TITLE
DownloadBuildArtifacts: Assertion error: 3482 == 0 in tunnel.js

### ISSUE THREAD

**Issue by cloudlene** [microsoft/azure-devops-node-api#380]
I use a self hosted 2016 Server VM.

### Environment
Node version: 6.17.1 (node) 10.17.0 (node10)
Npm version: default
OS and version: Windows Server 2016 Data Center
azure-devops-node-api version:  default
Agent version: 2.164.8

### Issue Description
Downloading build artifacts using YAML download keyword in 17 VMs in parallel using a matrix strategy.  Randomly on some machine the task throws the 3482 assertion error.

```
#azure-pipelines.yml
resources:
  pipelines:
    - pipeline: AppBuildToDeploy # Required when source == Specific
      source: App_Master_CI
      branch: master
      project: App
      trigger: none

#download.yml
- download: 'AppBuildToDeploy'
  patterns: ${{ parameters.itemPattern }}
  displayName: 'Download Specified Artifacts ${{ parameters.itemPattern }}'
  condition: and(succeeded(), ne(variables['skipBuildCopying'], 'true'))
```

### Expected behaviour
Download successfully on ALL machines

### Actual behaviour
Intermittently fails

### Steps to reproduce
1.  Download in parallel on a self hosted agent behind a proxy
2.  Randomly this error will popup
3.  Other machines / jobs run the same YAML to completion successfully

### Logs
```
2020-03-23T10:24:02.7359938Z ##[section]Starting: Download Specified Artifacts Drop/Artifacts/*_[A|B]*.zip
2020-03-23T10:24:02.7496402Z ==============================================================================
2020-03-23T10:24:02.7496592Z Task         : Download build artifacts
2020-03-23T10:24:02.7496656Z Description  : Download files that were saved as artifacts of a completed build
2020-03-23T10:24:02.7496754Z Version      : 0.156.1
2020-03-23T10:24:02.7496837Z Author       : Microsoft Corporation
2020-03-23T10:24:02.7496900Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-build-artifacts
2020-03-23T10:24:02.7496954Z ==============================================================================
2020-03-23T10:24:05.2677670Z Downloading artifacts for build: 62024
2020-03-23T10:24:05.3504149Z Downloading items from container resource #/1975617/Drop
2020-03-23T10:24:05.3505557Z Downloading artifact Drop from: https://dev.azure.com/ORGNAME//_apis/resources/Containers/1975617?itemPath=Drop&isShallow=true&api-version=4.1-preview.4
2020-03-23T10:24:40.4574070Z Skipped processing item Drop/test.md
2020-03-23T10:24:40.4584501Z Skipped processing item Drop/Artifacts/20.0.0.6173.zip
2020-03-23T10:24:40.7207668Z Downloading Drop/Artifacts/20.0.0.6173_AutomationBin.zip to C:\agent\_work\1\CPSBuildToDeploy\Drop\Artifacts\20.0.0.6173_AutomationBin.zip
2020-03-23T10:24:48.3333034Z Downloaded Drop/Artifacts/20.0.0.6173_AutomationBin.zip to C:\agent\_work\1\CPSBuildToDeploy\Drop\Artifacts\20.0.0.6173_AutomationBin.zip
2020-03-23T10:25:55.6275027Z ##[error]Unhandled: 3482 == 0
2020-03-23T10:25:55.6312995Z 
2020-03-23T10:25:55.6313352Z C:\agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.156.1\node_modules\artifact-engine\Engine\artifactEngine.js:162
2020-03-23T10:25:55.6313484Z     throw err;
2020-03-23T10:25:55.6313562Z     ^
2020-03-23T10:25:55.6313601Z AssertionError: 3482 == 0
2020-03-23T10:25:55.6313655Z     at ClientRequest.onConnect (C:\agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.156.1\node_modules\tunnel\lib\tunnel.js:143:14)
2020-03-23T10:25:55.6313733Z     at ClientRequest.g (events.js:292:16)
2020-03-23T10:25:55.6313772Z     at emitThree (events.js:116:13)
2020-03-23T10:25:55.6313836Z     at ClientRequest.emit (events.js:194:7)
2020-03-23T10:25:55.6313939Z     at Socket.socketOnData (_http_client.js:410:11)
2020-03-23T10:25:55.6314031Z     at emitOne (events.js:96:13)
2020-03-23T10:25:55.6314085Z     at Socket.emit (events.js:188:7)
2020-03-23T10:25:55.6314154Z     at readableAddChunk (_stream_readable.js:176:18)
2020-03-23T10:25:55.6314251Z     at Socket.Readable.push (_stream_readable.js:134:10)
2020-03-23T10:25:55.6314315Z     at TCP.onread (net.js:559:20)
2020-03-23T10:25:55.6913132Z ##[error]artifact-engine: unhandled exception AssertionError: 3482 == 0
2020-03-23T10:25:55.7249692Z ##[error]Exit code 7 returned from process: file name 'C:\agent\externals\node\bin\node.exe', arguments '"C:\agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.156.1\main.js"'.
2020-03-23T10:25:55.7257923Z ##[section]Finishing: Download Specified Artifacts Drop/Artifacts/*_[A|B]*.zip
```

I'm updating the agent to 2.165.2 & installing node using 11.x in the pipeline.  Will post back results.

**Comment by stephenmichaelf** [comment]
@fadnavistanmay could you take a look at this?

**Comment by stephenmichaelf** [comment]
@cloudlene Could you recreate this in the [tasks](https://github.com/microsoft/azure-pipelines-tasks) repo? Thanks!
