### ISSUE TITLE
Error while updating build definition. Property 'yamlFilename' no present in BuildProcess interface of BuildInterfaces.ts file

### ISSUE THREAD

**Issue by csharpdocs** [microsoft/azure-devops-node-api#399]
Hi Team,

I am currently using azure-devops-node-api to trigger my build pipeline using azure functions.
I wanted to update my build definition. While development I found the property with name 'yamlFilename' is not present in BuildInterface.ts file's BuildProcess interface hence my code was breaking while updating build definition. I manually added this property(yamlFilename?: string;) in my code(npm package) locally and it worked. I request you to update BuildInterface.ts files BuildProcess interface with additional property yamlFilename?: string; 

The interface should be ideally like below

export interface BuildProcess {
    /**
     * The type of the process.
     */
    type?: number;
    yamlFilename?: string;    
}

### Environment
Node version: 14.0.13
Npm version: 6.1.0
OS and version: Windows 7
azure-devops-node-api version: 10.1.1

### Issue Description
I am currently using azure-devops-node-api to trigger my build pipeline using azure functions.
I wanted to update my build definition. While development I found the property with name 'yamlFilename' is not present in BuildInterface.ts file's BuildProcess interface hence my code was breaking while updating build definition. I manually added this property(yamlFilename?: string;) in my code(npm package) locally and it worked.

### Expected behaviour
I should be able to update build definition

### Actual behaviour
Throwing error while updating build definition

### Steps to reproduce

Step 1: Create typescript based project with build api client to update build definition

let authHandler = azdev.getPersonalAccessTokenHandler(token);
let connection = new azdev.WebApi(organizationUrl, authHandler);
let buildApi: ba.BuildApi = await connection.getBuildApi(); 

Step 2: Retrive existing build definition

let buildDefinition = await buildApi.getDefinition("myproject", 4);
console.log("MESSAGE: Existing build definition");  

Step 3: Print build definition and you would see process: { type: 2, yamlFilename: '/azure-pipelines.yml' },

[19-06-2020 12:06:25] MESSAGE: Existing build definition
[19-06-2020 12:06:25]      badge:
[19-06-2020 12:06:25]       { href:
[19-06-2020 12:06:25]          'https://dev.azure.com/myorg/e367604a-08f8-466f-a1c5-0are321bea0/_apis/build/status/4' } },
[19-06-2020 12:06:25]   comment: 'your build definition comment goes here',
[19-06-2020 12:06:25]   description: 'your build definition comment description goes here',
[19-06-2020 12:06:25]   jobAuthorizationScope: 1,
[19-06-2020 12:06:25]   process: { type: 2, yamlFilename: '/azure-pipelines.yml' },
[19-06-2020 12:06:25]   repository:
[19-06-2020 12:06:25]    { name: 'azure-devops-sample-pipelines',
[19-06-2020 12:06:25]      url:
[19-06-2020 12:06:25]       'https://dev.azure.com/myorg/myproj/_git/azure-devops-sample-pipelines',
[19-06-2020 12:06:25]      defaultBranch: 'refs/heads/master',
[19-06-2020 12:06:25]      type: 'TfsGit' },
[19-06-2020 12:06:25]   quality: 1,
[19-06-2020 12:06:25]   authoredBy:

Step 4:
Now try to update build definition

const taskAgentPoolReference : bi.TaskAgentPoolReference = {
            "name" : "Hosted VS2019",
            "isHosted" : true
        }

        const agentPoolQueue : bi.AgentPoolQueue = {
            pool: taskAgentPoolReference
        }

const buildProcess : bi.BuildProcess = {
            "type" : 2
        }

 // Update build definition
        console.log("MESSAGE: Updating build definition");
        await buildApi.updateDefinition(buildDefinition, myProjectName, buildDefinition.id); 

This throws error below
[19-06-2020 18:52:12] MESSAGE: Updating build definition
[19-06-2020 18:52:17] Executed 'Functions.HttpInvokeAzureDevOpsBuildPipeline' (Failed, Id=5f0cd2c4-1886-4aed-9cdd-2c6030fb9918)
[19-06-2020 18:52:17] System.Private.CoreLib: Exception while executing function: Functions.HttpInvokeAzureDevOpsBuildPipeline. System.Private.CoreLib: Result: Failure
Exception: Error: TF400898: An Internal Error Occurred. Activity Id: 16b78e6a-3a38-4459-88e0-4c3a405872e4.
Stack: Error: TF400898: An Internal Error Occurred. Activity Id: 16b78e6a-3a38-4459-88e0-4c3a405872e4.
    at RestClient.<anonymous> (F:\Practice\azure-functionapp-typescript\node_modules\typed-rest-client\RestClient.js:202:31)
    at Generator.next (<anonymous>)
    at fulfilled (F:\Practice\azure-functionapp-typescript\node_modules\typed-rest-client\RestClient.js:6:58)
    at process._tickCallback (internal/process/next_tick.js:68:7).

Conclusion:
According to documentation https://github.com/microsoft/azure-devops-node-api/blob/master/api/interfaces/BuildInterfaces.ts

Interface BuildProcess dont have 'yamlFilename' property and hence while updating my build definition code breaks

[19-06-2020 12:06:25] MESSAGE: Existing build definition
[19-06-2020 12:06:25]      badge:
[19-06-2020 12:06:25]       { href:
[19-06-2020 12:06:25]          'https://dev.azure.com/myorg/e367604a-08f8-466f-a1c5-0are321bea0/_apis/build/status/4' } },
[19-06-2020 12:06:25]   comment: 'your build definition comment goes here',
[19-06-2020 12:06:25]   description: 'your build definition comment description goes here',
[19-06-2020 12:06:25]   jobAuthorizationScope: 1,
[19-06-2020 12:06:25]   process: { type: 2, **yamlFilename: '/azure-pipelines.yml'** },
[19-06-2020 12:06:25]   repository:
[19-06-2020 12:06:25]    { name: 'azure-devops-sample-pipelines',
[19-06-2020 12:06:25]      url:
[19-06-2020 12:06:25]       'https://dev.azure.com/myorg/myproj/_git/azure-devops-sample-pipelines',
[19-06-2020 12:06:25]      defaultBranch: 'refs/heads/master',
[19-06-2020 12:06:25]      type: 'TfsGit' },
[19-06-2020 12:06:25]   quality: 1,
[19-06-2020 12:06:25]   authoredBy:

Alternatively you can also see response of API https://dev.azure.com/{organization}/{project}/_apis/build/definitions/{definitionId}?api-version=5.1

it also returns  process: { type: 2, **yamlFilename: '/azure-pipelines.yml'** }

**Comment by csharpdocs** [comment]
I found the solution!!

The class 'YamlProcess' is inherited from 'BuildProcess' interface.

I replaced my code 
const buildProcess : bi.BuildProcess = {
            "type" : 2
        }

to 

const buildProcess : bi.YamlProcess = {
            "type" : 2,
            "yamlFilename": "/" + automationPipelineFileName
        }

and it Worked
