### ISSUE TITLE
Update variable group fails 

### ISSUE THREAD

**Issue by cyuste** [microsoft/azure-devops-node-api#424]
### Environment
Node version: v14.9.0
OS and version: osx big sur
azure-devops-node-api version: 10.1.2

### Issue Description
Trying to update a variable group fails with the following error:
`(node:27088) UnhandledPromiseRejectionWarning: Error: Project information name is not valid for variable group.`

### Expected behaviour
Variable group should be updated

### Actual behaviour
The error mentioned above

### Steps to reproduce
This code fails
```

const azdev = require('azure-devops-node-api')

const orgUrl = "https://dev.azure.com/ORG_NAME";
const token = SECRET_TOKEN; 
const authHandler = azdev.getPersonalAccessTokenHandler(token)
const azpConn = new azdev.WebApi(orgUrl, authHandler)

azpConn.getTaskAgentApi().then( (ta) => {
  ta.getVariableGroups("Project Name", "PublicVarsTest").then( (vgs) => {
      let varGroup = vgs[0]

      varGroup.variables["VAR_NAME"] = "xxx"
      ta.updateVariableGroup(varGroup, varGroup.id).then( (b) => {
        console.log(b)
      })
  })
})

```
But if I modify TaskAgentApiBase.js to use api version 5.0 (the only difference I see is that the URL contains the project name in the path) the code works fine

### Aditional logs

```
(node:27228) UnhandledPromiseRejectionWarning: Error: Project information name is not valid for variable group.
    at RestClient.<anonymous> (/Users/cyuste/Repos/aws-toolkit-azure-devops/node_modules/typed-rest-client/RestClient.js:202:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/cyuste/Repos/aws-toolkit-azure-devops/node_modules/typed-rest-client/RestClient.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
<node_internals>/internal/process/warning.js:41
(node:27228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
<node_internals>/internal/process/warning.js:41
(node:27228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cyuste** [comment]
Retested with package version 9.0.1 that uses api version `5.1-preview.1`, it works fine (I had to change the call to updateVariableGroup as it requests the project name as parameter)

**Comment by cyuste** [comment]
does anybody maintain this repo?

**Comment by jmeaster30** [comment]
This issue is still happening with azure-devops-node-api version 11.1.1 and variable group api version 6.1-preview.2.

Is there a solution to this issue?

**Comment by Ric43** [comment]
16 April 2022 - still an issue using API version 6.0-preview.2 (or just 6.0 for that matter)

Error message:
    "message": "Project information name is not valid for variable group.",
    "typeName": "System.ArgumentException, mscorlib",
    "typeKey": "ArgumentException",
    "errorCode": 0,
    "eventId": 0

Using api version 5.1-preview.1 works.

**Comment by adumitreseibogdan** [comment]
Why was this issue closed ? Can it be reopened, because this issue still occurs.

Using api version 5.1-preview.1 works.

Using api version 6.0-preview.2  or 6.0 doesn't.

**Comment by chassq** [comment]
This is still a problem with the C# sdk. It is broken in latest stable and latest preview. The allowed call is (no name param is available to pass):

`await client.UpdateVariableGroupAsync(variableGroup.Id, variableParams, cancellationToken: cancellationToken);`

The error is:
```
Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Project information name is not valid for variable group.
 ---> System.ArgumentException: Project information name is not valid for variable group.
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Atmc.IaC.CLI.Services.DevOps.DevOpsVariableGroupService.ListVariableGroup(CancellationToken cancellationToken) in Services\DevOps\DevOpsVariableGroupService.cs:line 86
   at Atmc.IaC.CLI.ProgramProcess.Process(IArgParserOptions argOptions, CancellationToken cancellationToken) in ProgramProcess.cs:line 78
   at Atmc.IaC.CLI.Program.Main(String[] args) in Atmc.IaC\Atmc.IaC\CLI\Program.cs:line 33
```
