### ISSUE TITLE
Error when trying to call "getPersonalAccessTokenHandler()" method

### ISSUE THREAD

**Issue by ChenLuigi** [microsoft/azure-devops-node-api#463]
### Environment
Node version: v14.17.5
Npm version: 6.14.14
OS and version:  windows-2019
azure-devops-node-api version: 11.0.1 

### Issue Description
We are using the library "azure-devops-node-api version" in our plugin to authenticate with AZDO, and we have faced an issue when we have released our latest plugin version (8.15.2021), the method "getPersonalAccessTokenHandler()" throws the following error :

##[warning]LIB_ResourceFile does not exist
##[debug]Processed: ##vso[task.issue type=warning;]LIB_ResourceFile does not exist
RangeError: Maximum call stack size exceeded
    at N (C:\agent\_work\_tasks\WhiteSource_cd7fbc44-4efb-43e5-bc7b-482b4ba02ead\1.0.427\dist\bundle.js:2:5588184)
    at N (C:\agent\_work\_tasks\WhiteSource_cd7fbc44-4efb-43e5-bc7b-482b4ba02ead\1.0.427\dist\bundle.js:2:5588393)
    at N (C:\agent\_work\_tasks\WhiteSource_cd7fbc44-4efb-43e5-bc7b-482b4ba02ead\1.0.427\dist\bundle.js:2:5588393)
    at N (C:\agent\_work\_tasks\WhiteSource_cd7fbc44-4efb-43e5-bc7b-482b4ba02ead\1.0.427\dist\bundle.js:2:5588393)
    at N (C:\agent\_work\_tasks\WhiteSource_cd7fbc44-4efb-43e5-bc7b-482b4ba02ead\1.0.427\dist\bundle.js:2:5588393)
    at N (C:\agent\_work\_tasks\WhiteSource_cd7fbc44-4efb-43e5-bc7b-482b4ba02ead\1.0.427\dist\bundle.js:2:5588393)
    at N (C:\agent\_work\_tasks\WhiteSource_cd7fbc44-4efb-43e5-bc7b-482b4ba02ead\1.0.427\dist\bundle.js:2:5588393)
    at N (C:\agent\_work\_tasks\WhiteSource_cd7fbc44-4efb-43e5-bc7b-482b4ba02ead\1.0.427\dist\bundle.js:2:5588393)
    at N (C:\agent\_work\_tasks\WhiteSource_cd7fbc44-4efb-43e5-bc7b-482b4ba02ead\1.0.427\dist\bundle.js:2:5588393)
    at N (C:\agent\_work\_tasks\WhiteSource_cd7fbc44-4efb-43e5-bc7b-482b4ba02ead\1.0.427\dist\bundle.js:2:5588393)

To fix the issue we have downgraded the version of the library ("azure-devops-node-api version") to be "9.0.1".
I have to mention that we didn't change the plugin content and we verify that this library is the root cause of this issue.

### Expected behavior
The method "getPersonalAccessTokenHandler()" should work without any issues.

### Actual behavior
The plugin task could not finish successfully and throws an error.

**Comment by kuleshovilya** [comment]
Hello @ChenLuigi 
That is really abastract, could you please get into more details on how it's implemented, where the error is thrown, maybe provide full error logs if possible.
You can privately reach me with the details at v-ikuleshov@microsoft.com

**Comment by kuleshovilya** [comment]
Any update on the issue?

**Comment by kuleshovilya** [comment]
@ChenLuigi I'll close the issue for now, due to the lack of answer. If something comes up, you can reopen the ticket or ping me at v-ikuleshov@microsoft.com
