### ISSUE TITLE
Updating pull request threads and comments

### ISSUE THREAD

**Issue by eduherminio** [microsoft/azure-devops-node-api#497]
### Environment
Node version: 
Npm version: 
OS and version: 
azure-devops-node-api version: 

### Issue Description

First of all, apologies since I'm fully aware this is not the right place to post this issue.
But hopefully someone can guide me about where to post it and/or if it's likely to be an API issue or a misuse of the client.

While being authenticated using a PAT token I'm trying to update a thread (or a comment) that I created using that same PAT token.
In fact, after some debugging, I'm trying to send back literally the same items I get from the API, but still failing to updated them, seeing the following error from the API in both cases:

```
An author of a comment cannot be updated.
Parameter name: Author
```

Code fragment: calling `client.GetThreadsAsync()` and right after, trying to call `client.UpdateThreadAsync()` and `client.UpdateCommentAsync`. Is there any extra step required when using the node api to update a comment?

```csharp
    public async Task GetThread(string orgName, string repoId, int pullRequestId, int threadId)
    {
        using var connection = new VssConnection(new Uri($"https://dev.azure.com/{orgName}/"), new VssBasicCredential(string.Empty, "my_token"));
        using var gitClient = await connection.GetClientAsync<ThrottledGitHttpClient>();

        var thread = (await gitClient.GetThreadsAsync(repoId, pullRequestId))?.FirstOrDefault(t => t.Id == threadId);
        await gitClient.UpdateThreadAsync(thread, repoId, pullRequestId, thread.Id);    // Error
        
        var comment = thread.Comments.FirstOrDefault();    // my_token user's comment
        await gitClient.UpdateCommentAsync(comment, repoId, pullRequestId, threadId, comment.Id);     // Error
    }
```

### Logs
<details>
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: An author of a comment cannot be updated.
      Parameter name: Author
       ---> System.ArgumentException: An author of a comment cannot be updated.
      Parameter name: Author
         --- End of inner exception stack trace ---

   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PRHub.Services.AzureDevOpsService.<GetThread>d__5.MoveNext() in C:\dev\prhub\teams-prhub\api\src\PRHub\Services\AzureDevOpsService.cs:line 53
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PRHub.Services.ThreadService.<UpdateComment>d__8.MoveNext() in C:\dev\prhub\teams-prhub\api\src\PRHub\Services\ThreadService.cs:line 114
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PRHub.Api.Controllers.ThreadController.<Update>d__3.MoveNext() in C:\dev\prhub\teams-prhub\api\src\PRHub.Api\Controllers\ThreadController.cs:line 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.<Execute>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeNextActionFilterAsync>g__Awaited|10_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeInnerFilterAsync>g__Awaited|13_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeNextExceptionFilterAsync>g__Awaited|26_0>d.MoveNext()
</details>

**Comment by eduherminio** [comment]
Thanks, asked it [there](https://developercommunity.visualstudio.com/t/Updating-AzureDevOps-Pull-Request-Thread/10005281).
