### ISSUE TITLE
UpdateVariableGroupAsync is still a problem with the C# sdk. It is broken in latest stable and latest preview.

### ISSUE THREAD

**Issue by chassq** [microsoft/azure-devops-node-api#572]
This is still a problem with the C# sdk. It is broken in latest stable and latest preview. The allowed call is (no name param is available to pass):

`await client.UpdateVariableGroupAsync(variableGroup.Id, variableParams, cancellationToken: cancellationToken);`

The error is:
```
Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Project information name is not valid for variable group.
 ---> System.ArgumentException: Project information name is not valid for variable group.
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Atmc.IaC.CLI.Services.DevOps.DevOpsVariableGroupService.ListVariableGroup(CancellationToken cancellationToken) in Services\DevOps\DevOpsVariableGroupService.cs:line 86
   at Atmc.IaC.CLI.ProgramProcess.Process(IArgParserOptions argOptions, CancellationToken cancellationToken) in ProgramProcess.cs:line 78
   at Atmc.IaC.CLI.Program.Main(String[] args) in Atmc.IaC\Atmc.IaC\CLI\Program.cs:line 33
```

_Originally posted by @chassq in https://github.com/microsoft/azure-devops-node-api/issues/424#issuecomment-1760181213_

**Comment by kirill-ivlev** [comment]
Hi @chassq,
thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by chassq** [comment]
@kirill-ivlev Thanks for the update! Much appreciated. Hope this is resolved soon as it is blocking us a bit. As a workaround we have reverted to the REST api for now.

**Comment by chassq** [comment]
Any update on when this might be consdiered?
